[project]
name = "winter-break"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "apprise>=1.9.6",
    "boto3>=1.42.18",
    "pandas>=2.3.3",
    "polars>=1.36.1",
    "prefect>=3.6.8",
    "prefect-aws>=0.5.13",
    "pulumi>=3.214.0",
    "pulumi-aws>=7.15.0",
    "pydantic>=2.12.5",
    "streamlit>=1.52.2",
]
